services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data:
