name: Frontend CI

defaults:
  run:
    working-directory: web

on:
  pull_request:
    paths:
      - "web/**"
  push:
    paths:
      - "web/**"
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint
          - build

    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Node.js 24
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
