name: Frontend CI

defaults:
  run:
    working-directory: web

on:
  pull_request:
    paths:
      - "web/**"
  push:
    paths:
      - "web/**"
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint
          - build

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Node.js 24
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
